services:
  app:
    build:
      target: base
      context: ./origin
    entrypoint: script/docker-entrypoint.sh
    command: npm run dev
    volumes:
      - ./origin:/app:cached
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: false
    stdin_open: true
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  postgresql-data:
