steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/my-origin-test:$TAG_NAME
      - --cache=false
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
